name: CI

on: 
  pull_request:
    types: [opened]

jobs:
  todo-fixme-comment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: get yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache key and directory for node_modules cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: yarn
        run: yarn --frozen-lockfile
      - id: find-pull-request
        uses: jwalton/gh-find-current-pr@v1
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - name: create TODO/FIXME comment body
        id: comment-body
        run: |
          yarn todos --exit-nicely --reporter markdown > TODO.md
          body="$(sed 1,2d TODO.md)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo "::set-output name=body::$body"
      - name: post TODO/FIXME comment to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.find-pull-request.outputs.number }}
          body: ${{ steps.comment-body.outputs.body }}   
